//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace _70_516
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Region))]
    [KnownType(typeof(Employee))]
    public partial class Territory: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string TerritoryID
        {
            get { return _territoryID; }
            set
            {
                if (_territoryID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TerritoryID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _territoryID = value;
                    OnPropertyChanged("TerritoryID");
                }
            }
        }
        private string _territoryID;
    
        [DataMember]
        public string TerritoryDescription
        {
            get { return _territoryDescription; }
            set
            {
                if (_territoryDescription != value)
                {
                    _territoryDescription = value;
                    OnPropertyChanged("TerritoryDescription");
                }
            }
        }
        private string _territoryDescription;
    
        [DataMember]
        public int RegionID
        {
            get { return _regionID; }
            set
            {
                if (_regionID != value)
                {
                    ChangeTracker.RecordOriginalValue("RegionID", _regionID);
                    if (!IsDeserializing)
                    {
                        if (Region != null && Region.RegionID != value)
                        {
                            Region = null;
                        }
                    }
                    _regionID = value;
                    OnPropertyChanged("RegionID");
                }
            }
        }
        private int _regionID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Region Region
        {
            get { return _region; }
            set
            {
                if (!ReferenceEquals(_region, value))
                {
                    var previousValue = _region;
                    _region = value;
                    FixupRegion(previousValue);
                    OnNavigationPropertyChanged("Region");
                }
            }
        }
        private Region _region;
    
        [DataMember]
        public TrackableCollection<Employee> Employees
        {
            get
            {
                if (_employees == null)
                {
                    _employees = new TrackableCollection<Employee>();
                    _employees.CollectionChanged += FixupEmployees;
                }
                return _employees;
            }
            set
            {
                if (!ReferenceEquals(_employees, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_employees != null)
                    {
                        _employees.CollectionChanged -= FixupEmployees;
                    }
                    _employees = value;
                    if (_employees != null)
                    {
                        _employees.CollectionChanged += FixupEmployees;
                    }
                    OnNavigationPropertyChanged("Employees");
                }
            }
        }
        private TrackableCollection<Employee> _employees;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Region = null;
            Employees.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupRegion(Region previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Territories.Contains(this))
            {
                previousValue.Territories.Remove(this);
            }
    
            if (Region != null)
            {
                if (!Region.Territories.Contains(this))
                {
                    Region.Territories.Add(this);
                }
    
                RegionID = Region.RegionID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Region")
                    && (ChangeTracker.OriginalValues["Region"] == Region))
                {
                    ChangeTracker.OriginalValues.Remove("Region");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Region", previousValue);
                }
                if (Region != null && !Region.ChangeTracker.ChangeTrackingEnabled)
                {
                    Region.StartTracking();
                }
            }
        }
    
        private void FixupEmployees(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Employee item in e.NewItems)
                {
                    if (!item.Territories.Contains(this))
                    {
                        item.Territories.Add(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Employees", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Employee item in e.OldItems)
                {
                    if (item.Territories.Contains(this))
                    {
                        item.Territories.Remove(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Employees", item);
                    }
                }
            }
        }

        #endregion
    }
}
